name: Build and push docker iamge

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v7

      - name: Construir la imagen de docker
        run: docker build -t 512-pet-radar-api:latest .